### ISSUE TITLE
Is this just relevant for windows?

### ISSUE THREAD

**Issue by rscohn2** [matthew-brett/pip-legal#2]
If there is no license problem, would you only use intel compiler on windows or linux as well? I ask because it is a smaller step going from windows compiler to windows compiler + intel compiler vs introducing intel compiler for linux build, which is otherwise gcc.

**Comment by matthew-brett** [comment]
It's that's an open question.  I suspect it would take a strong argument to switch from gcc gfortran on Linux.  Having the standard build use tools that are freely available, makes it a lot easier to maintain.

**Comment by rscohn2** [comment]
It's been a while since I looked at windows, but my memory is that it is almost impossible to build on windows without relying on VC redistributables that are not open source. This has not stopped people from making GPL software available on Windows. Either people are just being practical or are interpreting VC redistributables to be part of [system library exception](https://www.gnu.org/licenses/gpl-faq.en.html#SystemLibraryException). I know Nathaniel was trying to put together a pure gcc toolchain, but cpython 2.7 is unlikely to adopt it so introducing intel compiler runtimes may not make a substantial difference with respect to GPL. This was the general feeling when I asked around intel for non-legal opinions on the issue.

**Comment by matthew-brett** [comment]
Right - I think the system library exception is the argument used.

I believe that an alternative compiler run-time library, statically or dynamically linked, would not qualify in this respect, but I can add that to the questions in the document - thanks for pointing that out.

The mingw-w64 default gcc toolchain links against the MSVCRT runtime, whereas the Python.org Windows installers link to specific MSVC runtimes (e.g. VC2008, VC2015).  It is possible to do non-default linking of mingw-w64 with runtimes before VC2015, but not the VC2015 runtime, and that's the current blocker for gcc - see https://mingwpy.github.io/issues.html#choice-of-msvc-runtime and following for some background.

**Comment by matthew-brett** [comment]
Do these changes cover the question, do think?  

https://github.com/matthew-brett/pip-legal/commit/3ccc65fd7c33d8cf8325ca9cbf0cfdb5dabd5963

**Comment by rscohn2** [comment]
It covers the question. Thanks.
